services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mountainpass_dev_mongo
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - /opt/mongo/dev:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    container_name: mountainpass_dev_mongo_express
    depends_on:
      - mongo
    restart: always
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017